### ISSUE TITLE
Graphic Proposals

### ISSUE THREAD

**Issue by DanNistor** [Kalon/blog#2]
Will come up! 

WE ARE ANONYMOUS AND WE WILL RULE THE WORLD !

**Comment by adrianolaru** [comment]
I totally agree Dan!

**Comment by DanNistor** [comment]
![kalon_blog](https://cloud.githubusercontent.com/assets/10955832/6186752/70a0b4ce-b386-11e4-93d6-d1c6f5930deb.png)

**Comment by adrianolaru** [comment]
Dan, you've sent an image with your awesome design, how 'bout adding it here, as well. :D

**Comment by maria** [comment]
He will :)

**Comment by adrianolaru** [comment]
I totally love dolphins...

**Comment by DanNistor** [comment]
I might love them too! Monday untill Lunch i'll share first itineration on Kalon Blog so keep on loving dolphins :-)

**Comment by DanNistor** [comment]
![1 kalon_blog](https://cloud.githubusercontent.com/assets/10955832/6212592/e5bdd4c4-b5ef-11e4-9be3-fdc483fbcdae.png)
![2 kalon_blog - menu](https://cloud.githubusercontent.com/assets/10955832/6212596/e5bfdf58-b5ef-11e4-8f1d-732455e496dc.png)
![3 kalon_blog - search results](https://cloud.githubusercontent.com/assets/10955832/6212593/e5beafde-b5ef-11e4-95d2-0c6136219787.png)
![4 kalon_blog - archieve](https://cloud.githubusercontent.com/assets/10955832/6212594/e5bed130-b5ef-11e4-9e12-9f223c6c110b.png)
![5 kalon_blog - single post](https://cloud.githubusercontent.com/assets/10955832/6212595/e5bf0c68-b5ef-11e4-97a4-e2f7fcc3da62.png)
